
name: wedzarnia
description: A simple app for ESP32 control with splash screen and WebView.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/wedzarnia_logo.png
